version: '3.0' # specify docker-compose version
networks:
  frontend:
    ipam:
      config:
        - subnet: 172.20.0.0/24
# Define the services/ containers to be run
services:
 angular: # name of the first service
  build: angularApp # specify the directory of the Dockerfile
  ports:
  - "8080:8080" # specify port mapping
 
 express: # name of the second service
  build: ./nodeBackend/ # specify the directory of the Dockerfile
  networks:
            frontend:
                ipv4_address: 172.20.0.2
  ports:
  - "3000:3000" #specify ports mapping
  links:
  - database # link this service to the database service
  depends_on:
    - database
 
 database: # name of the third service
  image: mongo # specify image to build container from
  networks:
            frontend:
                ipv4_address: 172.20.0.3
  ports:
  - "27017:27017" # specify port forwarding
  expose:
      - '27017'